---
title: "2.1-recoding-qualitycontrol"
author: "Justin Guerra"
date: "2023-09-06"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries needed
library(tidyverse)  # most variable creation here uses tidyverse 
library(tidyselect) # used to select variables in FP_EVENTS.R
library(haven)      # used for Haven labeled DHSvariables
library(labelled)   # used for Haven labeled variable creation
library(expss)    # for creating tables with Haven labeled df
library(readxl)     # for exporting to excel
library(naniar)   # to use replace_with_na function
library(here)       # to get R project path
library(sjlabelled) # to set variables label
library(survey)  # to calculate weighted ratio for GAR
library(Hmisc)
library(tidyr)

```

```{r}
path <- "/Users/justi/OneDrive/Desktop/colabo_data/data/"
#path <- "data/DHS-2019-21/"
datafile <- "recoded.rda"
load(file = "/Users/justi/OneDrive/Desktop/colabo_data/data/recoded.rda")
```

# Quality control functions in R
```{r}
#Checking over the variables that have all missing values
all_na.test <-  function(data){
  all(is.na(data))
}

#Checking over the variables that have categorical variables
character.test <- function(data){
  
  sapply(data, is.character) %>%
    which()
  
}

```

```{r}
character_variables = character.test(df) %>% 
  names()

character_variables
```
Strategic plan: Use one-hot encoding to encode multiple categorical variables into binary variables (1s and 0s) for machine learning 

```{r}
quality_controlflr = "/Users/justi/OneDrive/Desktop/colabo_infant_malnutrition/quality_control/"
dir.create(quality_controlflr)

write.table(character_variables,
            file = paste0(quality_controlflr, "character_variables.txt"),
            quote = FALSE,
            sep = "\t",
            row.names = FALSE,
            col.names = FALSE)
```


#Finding variables with all NAs
```{r}
all_NA_vars = sapply(df,all_na.test) %>%
  which() %>% 
  names()

all_NA_vars 
```


Strategic plan: Go check over the variables that have missing (not use variables that encode to other variables or identifiers) and revise them if needed

```{r}
write.table(all_NA_vars,
            file = paste0(quality_controlflr, "all_NA_variables.txt"),
            quote = FALSE,
            sep = "\t",
            row.names = FALSE,
            col.names = FALSE)
```

