---
title: "UMAP_Removed_NAs"
author: "Justin Guerra"
date: "2024-01-09"
output: html_document
---

UMAP Vizualization: Using the model validation code with removal of NAs (using NA omit), we are making the UMAP visualization using ggplot2


```{r setup, include=FALSE}
library(Hmisc)
library(rms)
library(glmnet)
library(dplyr)
library(imputeTS)
library(mice)
library(ROCit)
library(pROC)
library(ggplot2)
```


```{r}
path <- "/Users/justi/OneDrive/Desktop/colabo_data/data/recoded.rda"
#path <- "data/DHS-2019-21/"

load(file = path)
```



```{r}
model_vars <- c("maternal_height_4feet8inches_to_less_5feetinches",
                "maternal_height_less_4feet8inches",
                "maternal_edu_no",
                "maternal_edu_1_7",
                "maternal_edu_greater_7_10",
                "sex_male",
                "pre_birth_interval_less_than_equal_to_24_months",
                "birth_weight_less_than_1800_g",
                "birth_weight_1800_g_2500_g",
                "num_siblings_two_or_more",
                "low_caste",
                "toliet_access_no",
                "house_partially_finished_no",
                "separate_kitchen_no",
                "cooking_fuel_solid",
                "use_soap",
                "Northeast_focus",
                "Other_Focus",
                "mean_district_CIAF_40_49.9",
                "mean_district_CIAF_50_59.9",
                "mean_district_CIAF_60_69.9",
                "mean_district_CIAF_70_79.9",
                "mean_district_CIAF_80_89.9",
                "ciaf")

model_coeffs <- c(intercept = -1.62,  
                  maternal_height_4feet8inches_to_less_5feetinches = 0.34, 
                  maternal_height_less_4feet8inches = 0.79,
                  maternal_edu_no = 0.45,
                  maternal_edu_1_7 = 0.30,
                  maternal_edu_greater_7_10 = 0.17,
                  sex_male = 0.10,
                  pre_birth_interval_less_than_equal_to_24_months = 0.23,
                  birth_weight_less_than_1800_g = 0.88,
                  birth_weight_1800_g_2500_g = 0.46,
                  num_siblings_two_or_more = 0.07,
                  low_caste = 0.14,
                  toliet_access_no = 0.18,
                  house_partially_finished_no = 0.12,
                  separate_kitchen_no = 0.07,
                  cooking_fuel_solid = 0.07,
                  use_soap = 0.07,
                  Northeast_focus = -0.16,
                  Other_Focus = -0.23,
                  mean_district_CIAF_40_49.9 = 0.29,
                  mean_district_CIAF_50_59.9 = 0.60,
                  mean_district_CIAF_60_69.9 = 0.87,
                  mean_district_CIAF_70_79.9 = 1.11,
                  mean_district_CIAF_80_89.9 = 1.64)

df_model <- df[, model_vars] 

df_model_nona <- na.omit(df_model) %>%
  dplyr::mutate_if(is.factor, as.character) %>% #Change from factor to character (some reason converting 0s and 1s to 1s and 2s)
   dplyr::mutate_if(is.character, as.integer) #Change from character to integer
```

## UMAP Plot
```{r}
ciaf = df_model_nona$ciaf %>% replace(df_model_nona$ciaf == 1, "Malnourished") %>% 
  replace(df_model_nona$ciaf == 0, "Not Malnourished")
  

Umap_dfmodel_nona = umap::umap(d = df_model_nona)

```

```{r}
#Dataframe of Umap
Umap_df = Umap_dfmodel_nona$layout %>% as.data.frame()
colnames(Umap_df) = c("x", "y")


Umap_ggplot2 = ggplot() +
  geom_point(data = Umap_df, aes(x = x, y = y, color = ciaf)) +
   scale_color_manual(values = c("Malnourished" = "#DF536B", 
                                 "Not Malnourished" = "#61D04F")) +
  ggtitle(label = "UMAP Validation Plot (Removed NA)") +
  theme_classic()
```

```{r}
pdf(file = "/Users/justi/OneDrive/Desktop/colabo_infant_malnutrition/Umap_Visualizations/UMAP_removedNA_plot.pdf",
    height =  10,
    width = 10)

Umap_ggplot2

dev.off()
```
