---
title: "4.1 Feature Selection/Machine Learning"
author: "Justin Guerra"
date: "2023-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries needed
library(tidyverse)  # most variable creation here uses tidyverse 
library(tidyselect) # used to select variables in FP_EVENTS.R
library(haven)      # used for Haven labeled DHSvariables
library(labelled)   # used for Haven labeled variable creation
library(expss)    # for creating tables with Haven labeled df
library(readxl)     # for exporting to excel
library(naniar)   # to use replace_with_na function
library(here)       # to get R project path
library(sjlabelled) # to set variables label
library(survey)  # to calculate weighted ratio for GAR
library(Hmisc)
library(tidyr)
library(mltools)
library(stats)
library(randomForest)
library(DataExplorer)
library(corrplot)
library(ggplot2)
```

```{r}
#path <- "C:/Users/Arnav Gupta/R_Projects/Infant_Malnutrition/infant_malnutrition_stratification-main/data/recoded"
path <- "C:/Users/Arnav Gupta/R_Projects/Infant_Malnutrition/infant_malnutrition_stratification-main/data/recoded/"
datafile <- "recoded.rda"
load(paste0(path, datafile))
```


```{r}
pattern = "^v[0-9][0-9][0-9]*|^hv[0-9][0-9][0-9]*|^ml[0-9][0-9]*|^h[0-9][0-9]|^s[0-9][0-9][0-9]*|^shb[0-9][0-9][0-9]*|^h[a-z][0-9]*|^b[0-9]*|^sh[0-9]*|^m[0-9]*|^sb[0-9]*|^h[0-9]*|^v3a*|^sv[0-9]*|^je[0-9]*|awfact*|idx*|dptb*|flpv*"

var = stringr::str_detect(string = df %>% colnames(),
                     pattern = pattern)

var = var[!grepl("NA$", var)]

#selected_var = df[!var] %>% colnames()
selected_var = df[!colnames(df) %in% var]

```
```{r}

var_class = df[!var] %>% sapply(class) %>% unlist() %>% as.data.frame() %>% rownames_to_column(var = "variable_name")

character_variables = var_class %>% dplyr::filter(`.` == "character") %>% dplyr::select(variable_name) %>%
  dplyr::pull()

df[sapply(df, is.character)] <- lapply(df[sapply(df, is.character)], 
       as.factor)

factor_variables = var_class %>% dplyr::filter(`.` == "factor") %>% dplyr::select(variable_name) %>%
  dplyr::pull()

```

```{r}
onehot_encoding = one_hot(as.data.table(df[factor_variables]),
        naCols = TRUE,
        sparsifyNAs =TRUE)
onehot_encoding
```
```{r}
# importance_test <- randomForest(ciaf~ ., data= onehot_encoding, ntree = 10)
# importance(test)
# varImpPlot(test)
M = cor(onehot_encoding)
corrplot(M, type = "upper", tl.pos = "td",
         method = "circle", tl.cex = 0.1, tl.col = 'black', diag = FALSE)
```

```{r}
NA_OHE_vars = onehot_encoding %>% colnames() %>% str_subset(pattern = "_NA$")
onehot_encoding_noNAs = onehot_encoding %>% dplyr::select(-c(NA_OHE_vars, "ciaf_0"))
onehot_encoding_noNAs_vars = onehot_encoding_noNAs[, colSums(onehot_encoding_noNAs != 0) > 0] %>% as.data.frame()
colnames(onehot_encoding_noNAs_vars) = "1st Criteria"
```

```{r}
onehot_encoding_noNAs_vars %>% filter(rownames(onehot_encoding_noNAs_vars) != c("elig_1", "child_alive_1"))

```


```{r}
onehot_encoding_noNAs_diff_vars = onehot_encoding_noNAs_vars %>% filter(`1st Criteria` == TRUE) %>% rownames()
```

```{r}
chisq_test = vector(mode = "list")
chisq_df = vector(mode = "list")

for(feature in onehot_encoding_noNAs_diff_vars[ !(onehot_encoding_noNAs_diff_vars %in% c("elig_1", "child_alive_1", "christian_0"))]){
  
  chisq_test[[feature]] = chisq.test(x = onehot_encoding_noNAs[[feature]],
                                     y =  onehot_encoding_noNAs[["ciaf_1"]])
  
  chisq_df[[feature]] = data.frame(test_statistic = chisq_test[[feature]]$statistic,
             p_value = chisq_test[[feature]]$p.value,
             row.names = feature)  %>% 
    arrange(p_value) %>%
  dplyr::mutate(p_value_adj = p.adjust(p_value, method = "BH")) 
}


FeatureSelection_chisquared = do.call("rbind", chisq_df) %>% arrange(desc(test_statistic))
```

```{r}
write.table(x = FeatureSelection_chisquared[!(rownames(FeatureSelection_chisquared) %in% "ciaf_1"), ] %>% rownames_to_column(var = "Feature"),
            file = "C:/Users/justi/OneDrive/Desktop/colabo_infant_malnutrition/Feature_selection/Chi_squared_feature_selection.txt",
            quote = FALSE,
            sep = "\t",
            row.names = FALSE,
            col.names = TRUE)

```




