---
title: "4.1 Feature Selection/Machine Learning"
author: "Justin Guerra"
date: "2023-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries needed

#library(tidyselect) # used to select variables in FP_EVENTS.R
#library(haven)      # used for Haven labeled DHSvariables
#library(labelled)   # used for Haven labeled variable creation
#library(expss)    # for creating tables with Haven labeled df
#library(readxl)     # for exporting to excel
#library(naniar)   # to use replace_with_na function

#library(sjlabelled) # to set variables label
#library(survey)  # to calculate weighted ratio for GAR
#library(Hmisc)
#library(tidyr)
#library(mltools)
#library(stats)

library(here)       # to get R project path
library(tidyverse)  # most variable creation here uses tidyverse 
library(dplyr)
```

```{r}
#path <- "/Users/justi/OneDrive/Desktop/colabo_data/data/"
path <- "data/DHS-2019-21/"
dffile <- "recoded.rda"
load(file = here(path, dffile))

rvfile <- "recoded-variables.txt"
recoded_vars <- read.table(here(path, rvfile), header = FALSE)$V1
```

```{r}
for (col in recoded_vars) {
  if (!col %in% colnames(df)) {
    print(paste0("Column ",col, " is missing!"))
  }
}
```

```{r}
dfr <- df[recoded_vars]
dfr
```

```{r}
# Some utilities

get_class_of_columns <- function(df) {
  col_names <- colnames(df)
  classes <- df %>% sapply(class)
  col_class <- c()
  for (name in col_names) {
    c <- classes[[name]]
    ccl <- c[1]
    col_class <- append(col_class, ccl)
  }
  df_class <- data.frame(variable_name = col_names, variable_class = col_class)
  return(df_class)
}

convert_bin_factor_to_integer <- function(df) {
  for (col_name in names(df)) {
    # Check if the column is a factor and only contains 0 and 1
    if (is.factor(df[[col_name]]) && all(levels(df[[col_name]]) %in% c("0", "1"))) {
      print(paste0("Converting ", col_name, " into integer"))
      df[[col_name]] <- as.integer(as.character(df[[col_name]]))
    }
  }
}
```

```{r}
var_class <- get_class_of_columns(dfr)
var_class
```

```{r}
unique(var_class$variable_class)
```

```{r}
character_variables = var_class %>% dplyr::filter(variable_class == "character") %>% dplyr::select(variable_name) %>% dplyr::pull()
character_variables

# Converting character variables into factor
dfr[sapply(dfr, is.character)] <- lapply(dfr[sapply(dfr, is.character)], as.factor)
dfr
```

```{r}
numeric_variables = var_class %>% dplyr::filter(variable_class == "numeric") %>% dplyr::select(variable_name) %>% dplyr::pull()
numeric_variables
```
```{r}
integer_variables = var_class %>% dplyr::filter(variable_class == "integer") %>% dplyr::select(variable_name) %>% dplyr::pull()
integer_variables
```

```{r}
haven_variables = var_class %>% dplyr::filter(variable_class == "haven_labelled") %>% dplyr::select(variable_name) %>% dplyr::pull()
haven_variables
```

```{r}
haven_labelled_cols <- sapply(dfr, function(x) inherits(x, "haven_labelled"))
dfr[haven_labelled_cols] <- lapply(dfr[haven_labelled_cols], as.factor)
```

```{r}
factor_variables = var_class %>% dplyr::filter(variable_class == "factor") %>% dplyr::select(variable_name) %>% dplyr::pull()
factor_variables
```


```{r}
convert_bin_factor_to_integer(dfr)
```

```{r}
dfr
```

```{r}
var_class <- get_class_of_columns(dfr)
unique(var_class$variable_class)
```

```{r}
factor_variables = var_class %>% dplyr::filter(variable_class == "factor") %>% dplyr::select(variable_name) %>% dplyr::pull()
print(factor_variables)
```

```{r}
numeric_variables = var_class %>% dplyr::filter(variable_class == "numeric") %>% dplyr::select(variable_name) %>% dplyr::pull()
print(numeric_variables)
```

```{r}
integer_variables = var_class %>% dplyr::filter(variable_class == "integer") %>% dplyr::select(variable_name) %>% dplyr::pull()
print(integer_variables)
```


















```{r}
onehot_encoding = one_hot(as.data.table(df[factor_variables]),
        naCols = TRUE,
        sparsifyNAs =TRUE)
onehot_encoding
```

```{r}
df_nfactor <- df %>% select(-one_of(factor_variables))
df_nfactor
```

```{r}
dfc <- cbind(df_nfactor, onehot_encoding)
dfc
```

```{r}
all_na_columns <- which(colSums(is.na(dfc)) == nrow(dfc))
all_na_columns
```

```{r}
#dfc <- dfc[, -all_na_columns]
#dfc
dfc <- dfc %>% select(-one_of(names(all_na_columns)))
dfc
```

```{r}
rows_with_na <- sum(rowSums(is.na(df)) > 0)
print(rows_with_na)
```


```{r}
additional_rows_to_remove <- c("ssmod", "sdist", "sphase", "sweight", "sdweigh", "wgt", "wgt2", "waz", "whz", 
                               "sdweight", "defacto_child")
dfc <- dfc %>% select(-one_of(additional_rows_to_remove))
dfc
```
```{r}
dfc$b2 <- as.numeric(dfc$b2)
dfc$d4 <- as.numeric(dfc$d4)
dfc$f6 <- as.numeric(dfc$f6)

```

```{r}
dfc
#dfc[, haven_label_variables] <- lapply(dfc[, haven_label_variables], as.numeric)
```


```{r}
dfc
```

```{r}
formula_string <- paste(colnames(dfc), collapse = " + ")
formula_string <- paste0("~", formula_string)
formula_string
#eligch == 1

#ciaf_NA
#ciaf_0
#ciaf_1
```
```{r}
# Get the number of columns
num_cols <- ncol(dfc)

# Generate new column names
new_names <- paste0(letters[1:num_cols], 1:num_cols)
new_names

colnames(dfc) <- new_names

```


```{r}
library(mice)
dfc_imp <- mice(dfc,
     m = 3,
     maxit = 3)
```







```{r}
NA_OHE_vars = onehot_encoding %>% colnames() %>% str_subset(pattern = "_NA$")
onehot_encoding_noNAs = onehot_encoding %>% dplyr::select(-c(NA_OHE_vars, "ciaf_0"))
onehot_encoding_noNAs_vars = onehot_encoding_noNAs[, colSums(onehot_encoding_noNAs != 0) > 0] %>% as.data.frame()
colnames(onehot_encoding_noNAs_vars) = "1st Criteria"
```

```{r}
onehot_encoding_noNAs_vars %>% filter(rownames(onehot_encoding_noNAs_vars) != c("elig_1", "child_alive_1"))

```


```{r}
onehot_encoding_noNAs_diff_vars = onehot_encoding_noNAs_vars %>% filter(`1st Criteria` == TRUE) %>% rownames()
```

```{r}
selected_var
```
