---
title: "4.1 Feature Selection/Machine Learning"
author: "Justin Guerra"
date: "2023-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries needed
library(tidyverse)  # most variable creation here uses tidyverse 
library(tidyselect) # used to select variables in FP_EVENTS.R
library(haven)      # used for Haven labeled DHSvariables
library(labelled)   # used for Haven labeled variable creation
library(expss)    # for creating tables with Haven labeled df
library(readxl)     # for exporting to excel
library(naniar)   # to use replace_with_na function
library(here)       # to get R project path
library(sjlabelled) # to set variables label
library(survey)  # to calculate weighted ratio for GAR
library(Hmisc)
library(tidyr)
library(mltools)
library(stats)
```

```{r}
#path <- "/Users/justi/OneDrive/Desktop/colabo_data/data/"
path <- "data/DHS-2019-21/"
filename <- "recoded.rda"
load(file = here(path, filename))
```


```{r}
pattern = "^v[0-9][0-9][0-9]*|^hv[0-9][0-9][0-9]*|^ml[0-9][0-9]*|^h[0-9][0-9]|^s[0-9][0-9][0-9]*|^shb[0-9][0-9][0-9]*|^h[a-z][0-9]*|^b[0-9]*|^sh[0-9]*|^m[0-9]*|^sb[0-9]*|^h[0-9]*|^v3a*|^sv[0-9]*|^je[0-9]*|awfact*|idx*|dptb*|flpv*"

var = stringr::str_detect(string = df %>% colnames(),
                     pattern = pattern)
selected_var = df[!var] %>% colnames()
selected_var
```

```{r}
df <- df[selected_var]
df
```

```{r}
var_class = df %>% sapply(class) %>% unlist() %>% as.data.frame() %>% rownames_to_column(var = "variable_name")
var_class
```

```{r}
character_variables = var_class %>% dplyr::filter(`.` == "character") %>% dplyr::select(variable_name) %>%
  dplyr::pull()
character_variables
```

```{r}
df[sapply(df, is.character)] <- lapply(df[sapply(df, is.character)], 
       as.factor)
df
```

```{r}
var_class = df %>% sapply(class) %>% unlist() %>% as.data.frame() %>% rownames_to_column(var = "variable_name")
var_class
```

```{r}
factor_variables = var_class %>% dplyr::filter(`.` == "factor") %>% dplyr::select(variable_name) %>%
  dplyr::pull()
factor_variables
```


```{r}
onehot_encoding = one_hot(as.data.table(df[factor_variables]),
        naCols = TRUE,
        sparsifyNAs =TRUE)
onehot_encoding
```

```{r}
df_nfactor <- df %>% select(-one_of(factor_variables))
df_nfactor
```

```{r}
dfc <- cbind(df_nfactor, onehot_encoding)
dfc
```

```{r}
all_na_columns <- which(colSums(is.na(dfc)) == nrow(dfc))
all_na_columns
```

```{r}
#dfc <- dfc[, -all_na_columns]
#dfc
dfc <- dfc %>% select(-one_of(names(all_na_columns)))
dfc
```

```{r}
rows_with_na <- sum(rowSums(is.na(df)) > 0)
print(rows_with_na)
```


```{r}
additional_rows_to_remove <- c("ssmod", "sdist", "sphase", "sweight", "sdweigh", "wgt", "wgt2", "waz", "whz", 
                               "sdweight", "defacto_child")
dfc <- dfc %>% select(-one_of(additional_rows_to_remove))
dfc
```
```{r}
dfc$b2 <- as.numeric(dfc$b2)
dfc$d4 <- as.numeric(dfc$d4)
dfc$f6 <- as.numeric(dfc$f6)

```

```{r}
dfc
#dfc[, haven_label_variables] <- lapply(dfc[, haven_label_variables], as.numeric)
```


```{r}
dfc
```

```{r}
formula_string <- paste(colnames(dfc), collapse = " + ")
formula_string <- paste0("~", formula_string)
formula_string
#eligch == 1

#ciaf_NA
#ciaf_0
#ciaf_1
```
```{r}
# Get the number of columns
num_cols <- ncol(dfc)

# Generate new column names
new_names <- paste0(letters[1:num_cols], 1:num_cols)
new_names

colnames(dfc) <- new_names

```


```{r}
library(mice)
dfc_imp <- mice(dfc,
     m = 3,
     maxit = 3)
```







```{r}
NA_OHE_vars = onehot_encoding %>% colnames() %>% str_subset(pattern = "_NA$")
onehot_encoding_noNAs = onehot_encoding %>% dplyr::select(-c(NA_OHE_vars, "ciaf_0"))
onehot_encoding_noNAs_vars = onehot_encoding_noNAs[, colSums(onehot_encoding_noNAs != 0) > 0] %>% as.data.frame()
colnames(onehot_encoding_noNAs_vars) = "1st Criteria"
```

```{r}
onehot_encoding_noNAs_vars %>% filter(rownames(onehot_encoding_noNAs_vars) != c("elig_1", "child_alive_1"))

```


```{r}
onehot_encoding_noNAs_diff_vars = onehot_encoding_noNAs_vars %>% filter(`1st Criteria` == TRUE) %>% rownames()
```

```{r}
selected_var
```
