---
title: "Perm data analysis"
output: html_document
date: "2023-03-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries needed
library(tidyverse)  # most variable creation here uses tidyverse 
library(tidyselect) # used to select variables in FP_EVENTS.R
library(haven)      # used for Haven labeled DHSvariables
library(labelled)   # used for Haven labeled variable creation
library(expss)    # for creating tables with Haven labeled data
library(xlsx)     # for exporting to excel
library(naniar)   # to use replace_with_na function
library(here)       # to get R project path
library(sjlabelled) # to set variables label
library(survey)  # to calculate weighted ratio for GAR
```

```{r}
path <- "data/DHS-2019-21"
datafile <- "merged.rda"
load(here(path, datafile))
```

```{r}
df
```

```{r}
# Sample weights in DHS datasets
# Unit of analysis 				Variable 
# Households 		 				  hv005 
# Household members   		hv005 
# Women or children 			v005 
# Men 							      mv005 
# Domestic Violence 			d005 
# HIV test results 				hiv05 

# Stata code
#capture drop wgt
#generate wgt = hv005/1000000 
#gen wgt2 = 1
#*svyset [pw=wgt], psu(hv001) strata(hv022) singleunit(scaled)
#svyset hv001, weight(wgt) strata(hv022) , singleunit(centered) || _n, weight(wgt2) 


# Create wgt variable
df$wgt <- df$hv005 / 1000000

# Create wgt2 variable
df$wgt2 <- 1

# Set survey design
msvy <- svydesign(id = ~hv001, strata = ~hv022, data = df, weights = ~wgt)


# Set missing weigths to 1000000
#Mdata <- Mdata %>% mutate(hv005 = ifelse(is.na(hv005), 1000000, hv005))
# weight data
#msvy <- svydesign(id = Mdata$hv001, strata=Mdata$hv022, weights = Mdata$hv005/1000000, data=Mdata)
```

```{r}
# Identify eligible children

# Stata code
#capture drop eligch 
#gen eligch = 0 
#replace eligch = 1 if (hv103==1 & hc70 < 9996 & hc71 < 9996 & hc72 < 9996)

df <- df %>%
  mutate(
    eligch = 0,
    eligch = if_else(hv103 == 1 & hc70 < 9996 & hc71 < 9996 & hc72 < 9996, 1, eligch)
  )
```

```{r}
#capture drop real_id
#gen real_id =  real(string(hv001)+string(hv002)+string(hvidx))

#capture drop mother_id
#gen mother_id =  real(string(hv001)+string(hv002)+string(hv112))
#replace mother_id = . if midx == .

#capture drop father_id
#gen father_id =  real(string(hv001)+string(hv002)+string(hv114))
#replace father_id = . if midx == .

# Create the defacto_child variable
df$defacto_child <- df$hv103

# Generate mother_id using hv001, hv002, and hv112
df$mother_id <- as.numeric(paste0(df$hv001, df$hv002, df$hv112))

# Replace mother_id with NA if midx is NA
df$mother_id[is.na(df$midx)] <- NA

# Generate father_id using hv001, hv002, and hv114
df$father_id <- as.numeric(paste0(df$hv001, df$hv002, df$hv114))

# Replace father_id with NA if midx is NA
df$father_id[is.na(df$midx)] <- NA
```

```{r}
df$mother_id
```


```{r}
# Anthropometric variables 
# Age group
# State code
#capture drop age_group 
#recode child_age (0/5 = 0 "0. 0-5 mo")(6/11 = 1 "1. 6-11 mo")(12/17 = 2 "2. 12-17 mo") (18/24 = 3 "3. 18-24 mo")(25/59 = .),gen(age_group)
#recode child_age (0/5 = 0 "0. 0-5 mo")(6/11 = 1 "1. 6-11 mo")(12/17 = 2 "2. 12-17 mo") (18/23 = 3 "3. 18-23 mo") (24/35 = 4 "4. 24-35 mo")(36/47 = 5 "5. 36-47 mo")(48/59 = 6 "6. 48-60 mo"),gen(age_group_5y)

# Create new variable child_age with values from hc1
df$child_age <- df$hc1

# Recode child_age into age_group using specified ranges and labels
df$age_group <- cut(df$child_age, breaks = c(0, 5, 11, 17, 24, 59),
                    labels = c("0. 0-5 mo", "1. 6-11 mo", "2. 12-17 mo", "3. 18-24 mo", "."),
                    right = FALSE)

# Recode child_age into age_group_5y using specified ranges and labels
df$age_group_5y <- cut(df$child_age, breaks = c(0, 5, 11, 17, 23, 35, 47, 59),
                       labels = c("0. 0-5 mo", "1. 6-11 mo", "2. 12-17 mo", "3. 18-23 mo",
                                  "4. 24-35 mo", "5. 36-47 mo", "6. 48-60 mo"),
                       right = FALSE)

```


```{r}
df$age_group_5y
```


```{r}
base_model <- function(df) {
  # Calculate the linear term in the logistic function of the model
  # p(x) = 1 / (1+exp(-lp(x))
  lp = with(df, 
            -1.62 - 
              0.34*maternal_height_4feet8inches_to_less_5feetinches + 
              0.79*maternal_height_less_4feet8inches +
            
              ...
              )
  return(lp)
}
```

```{r}
data0 <- (...)
```

```{r}
source('./mdl-evaluation.R')
```

```{r}
pred0 <- unlist(map(1:nrow(data0), function(x) base_model(data0[x,]))) # prediction in log-odds (probabilities on logit scale)
prob0 <- 1 / (1 + exp(-pred0))
```

```{r}
# Generate the data frame with the data needed for the calibration and ROC plots
plot_data0 <- data.frame(out = data0$out, logodds = pred0, prob = prob0)

cal_plot(base_model, plot_data0, "prob", model_label = '', dir = mdl_folder0, fn = "cal_plot.pdf")
cal_c0 <- cal_coeff(plot_data0, "prob", mdl_folder0, "cal_plot_coefficients.txt")
print(cal_c0)

roc_plot(data0$out, prob0, dir = mdl_folder0, fn = "roc_plot.pdf")
```
