---
title: "Perm data analsys"
output: html_document
date: "2023-03-21"
---

From Stata to R
https://fsolt.org/blog/posts/switch-to-r/
https://epi-stats.github.io/Rtutorials/Stata_to_R#recode
https://www.techtips.surveydesign.com.au/post/the-recode-command


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries needed
library(tidyverse)  # most variable creation here uses tidyverse 
library(tidyselect) # used to select variables in FP_EVENTS.R
library(haven)      # used for Haven labeled DHSvariables
library(labelled)   # used for Haven labeled variable creation
library(expss)    # for creating tables with Haven labeled data
library(naniar)   # to use replace_with_na function
library(here)       # to get R project path
library(sjlabelled) # to set variables label
library(survey)  # to calculate weighted ratio for GAR
```

```{r}
# Household member data
HMpath <- "risk-model/data/DHS-2019-21/household-member"
HMdatafile <- "IAPR7EFL.DTA"
HMdata <- read_dta(here(HMpath, HMdatafile))
```

```{r}
# Children data
Cpath <- "risk-model/data/DHS-2019-21/children"
Cdatafile <- "IAKR7EFL.DTA"
Cdata <- read_dta(here(Cpath, Cdatafile))
```

```{r}
# Rename variables in children data to then merge with household
Cdata <- Cdata %>% rename("hv000" = "v000")
Cdata <- Cdata %>% rename("hv001" = "v001")
Cdata <- Cdata %>% rename("hv002" = "v002")
Cdata <- Cdata %>% rename("hvidx" = "b16")
```

```{r}
Cdata
```

```{r}
Mdata <- merge(HMdata, Cdata, by = c("hv000", "hv001", "hv002", "hvidx"), all.y = TRUE, all.x = TRUE)
```

```{r}
# Sample weights in DHS datasets
# Unit of analysis 				Variable 
# Households 		 				  hv005 
# Household members   		hv005 
# Women or children 			v005 
# Men 							      mv005 
# Domestic Violence 			d005 
# HIV test results 				hiv05 

# Stata code
#capture drop wgt
#generate wgt = hv005/1000000 
#gen wgt2 = 1
#*svyset [pw=wgt], psu(hv001) strata(hv022) singleunit(scaled)
#svyset hv001, weight(wgt) strata(hv022) , singleunit(centered) || _n, weight(wgt2) 

# Set missing weigths to 1000000
Mdata <- Mdata %>% mutate(hv005 = ifelse(is.na(hv005), 1000000, hv005))

# weight data
msvy <- svydesign(id = Mdata$hv001, strata=Mdata$hv022, weights = Mdata$hv005/1000000, data=Mdata)
```



```{r}
# Identify eligible children

# Stata code
#capture drop eligch 
#gen eligch = 0 
#replace eligch = 1 if (hv103==1 & hc70 < 9996 & hc71 < 9996 & hc72 < 9996)

Mdata <- Mdata %>% mutate(eligch = case_when(hv103 == 1 & hc70 < 996 & hc71 < 9996 & hc72 < 9996 ~ 1, TRUE ~ 0))
```


```{r}
# Anthropometric variables 

Mdata <- Mdata %>% rename("child_age" = "hc1")

# Age group
# State code
#capture drop age_group 
#recode child_age (0/5 = 0 "0. 0-5 mo")(6/11 = 1 "1. 6-11 mo")(12/17 = 2 "2. 12-17 mo") (18/24 = 3 "3. 18-24 mo")(25/59 = .),gen(age_group)
#recode child_age (0/5 = 0 "0. 0-5 mo")(6/11 = 1 "1. 6-11 mo")(12/17 = 2 "2. 12-17 mo") (18/23 = 3 "3. 18-23 mo") (24/35 = 4 "4. 24-35 mo")(36/47 = 5 "5. 36-47 mo")(48/59 = 6 "6. 48-60 mo"),gen(age_group_5y)


```

```{r}
load(file='/Users/justi/OneDrive/Desktop/colabo_data/data/recoding.rda')
```


```{r}
#
df$maternal_height_4feet8inches_to_less_5feetinches <- ifelse(df$maternal_height_cm > 142.24  & df$maternal_height_cm < 152.4, 1, 0)
df$maternal_height_less_4feet8inches <- ifelse(df$maternal_height_cm < 142.24, 1, 0)


df$maternal_edu_no <- ifelse(df$mother_education == 0, 1, 0)
df$maternal_edu_1_7 <- ifelse(df$mother_education >= 1 & df$mother_education <= 7,
                              1, 0)
df$maternal_edu_7_10 <- ifelse(df$mother_education >= 7 & df$mother_education <= 10,
                              1, 0)

df$sex_male <- ifelse(df$female == "0. male",
                                   1,
                                   0)

df$pre_birth_interval_less_than_equal_to_24_months <- ifelse(df$pre_birth_interval == "2. < 24 months", 1, 0)
df$birth_weight_less_than_1800_g <- ifelse(df$birthweight == "1. 1800g or less", 1, 0)
df$birth_weight_1800_g_2500_g <- ifelse(df$birthweight == "2. 1801 to 2500g", 1, 0)
df$num_siblings_two_or_more <- ifelse(df$siblings_bin == "2. 2 or more", 1, 0)
df$low_caste <- ifelse(df$low_caste == 1, 1, 0)
df$toliet_access_no <- ifelse(df$toilet_type == "0. no toilet", 1,0)
df$house_partially_finished_no <- ifelse(df$house_finish != "1. some concrete material", 1, 0)
df$separate_kitchen_no <- ifelse(df$kitchen == 0, 1,0)
df$cooking_fuel_solid <- ifelse(df$cooking_fuel == 0, 1, 0)
df$Northeast_focus <- ifelse(df$state_zones == "1. North-Eastern", 1, 0)
#df$Other_focus <- ifelse(df$state_zones == "")## check over
df$mean_district_CIAF_40_49.9 <- ifelse(df$ciaf_decile == "40%", 1, 0)
df$mean_district_CIAF_50_59.9 <- ifelse(df$ciaf_decile == "50%", 1, 0)
df$mean_district_CIAF_60_69.9 <- ifelse(df$ciaf_decile == "60%", 1, 0)
df$mean_district_CIAF_70_79.9 <- ifelse(df$ciaf_decile == "70%", 1, 0)
df$mean_district_CIAF_80_89.9 <- ifelse(df$ciaf_decile == "80%", 1, 0)
```

```{r}
df[,c("maternal_height_4feet8inches_to_less_5feetinches",
       "maternal_height_less_4feet8inches",
      "maternal_edu_no",
      "maternal_edu_1_7",
      "maternal_edu_7_10",
      "sex_male",
      "pre_birth_interval_less_than_equal_to_24_months",
      "birth_weight_less_than_1800_g",
      "num_siblings_two_or_more",
      "low_caste",
      "toliet_access_no",
      "house_partially_finished_no",
      "separate_kitchen_no",
      "cooking_fuel_solid",
      "Northeast_focus",
      "mean_district_CIAF_40_49.9",
      "mean_district_CIAF_50_59.9",
      "mean_district_CIAF_60_69.9",
      "mean_district_CIAF_70_79.9",
      "mean_district_CIAF_80_89.9")] %>% na.omit()
```

```{r}

base_model <- function(df) {
  # Calculate the linear term in the logistic function of the model
  # p(x) = 1 / (1+exp(-lp(x))
  lp = with(df, 
            -1.62 - 
              0.34 * maternal_height_4feet8inches_to_less_5feetinches + 
              0.79 * maternal_height_less_4feet8inches +
              0.45 * maternal_edu_no +
              0.30 * maternal_edu_1_7 +
              0.17 * maternal_edu_greater_7_10 +
              0.10 * sex_male +
              0.23 * pre_birth_interval_less_than_equal_to_24_months +
              0.88 * birth_weight_less_than_1800_g +
              0.46 * birth_weight_1800_g_2500_g +
              0.07 * num_siblings_two_or_more +
              0.14 * low_caste_yes +
              0.18 * toliet_access_no +
              0.12 * house_partially_finished_no +
              0.07 * separate_kitchen_no +
              0.07 * cooking_fuel_solid +
              0.07 * uses_soap_after_use +
              -0.16 * Northeast_focus +
              -0.23 * Other_focus +
              -0.09 * high_priority_district_yes +
              0.29 * mean_district_CIAF_40_49.9 +
              0.60 *  mean_district_CIAF_50_59.9 +
              0.87 *  mean_district_CIAF_60_69.9 +
              1.11 * mean_district_CIAF_70_79.9 +
              1.64 *  mean_district_CIAF_80_89.9
              )
  return(lp)
}

logistic_function = 1 / (1 + exp(-1 * lp))
```

```{r}
data0 <- (...)
```

```{r}
source('./mdl-evaluation.R')
```

```{r}
pred0 <- unlist(map(1:nrow(data0), function(x) base_model(data0[x,]))) # prediction in log-odds (probabilities on logit scale)
prob0 <- 1 / (1 + exp(-pred0))
```

```{r}
# Generate the data frame with the data needed for the calibration and ROC plots
plot_data0 <- data.frame(out = data0$out, logodds = pred0, prob = prob0)

cal_plot(base_model, plot_data0, "prob", model_label = '', dir = mdl_folder0, fn = "cal_plot.pdf")
cal_c0 <- cal_coeff(plot_data0, "prob", mdl_folder0, "cal_plot_coefficients.txt")
print(cal_c0)

roc_plot(data0$out, prob0, dir = mdl_folder0, fn = "roc_plot.pdf")
```
