---
title: "Data Imputation from Emperical Distribution With Factor Variables"
author: "Justin Guerra"
date: "2024-04-15"
output: html_document
---

```{r setup, include=FALSE}

rm(list = ls())
#library(mice)
library(missForest)
library(missMDA)
library(magrittr)
library(here) 
library(dplyr)
library(purrr)
library(fastDummies)

```

https://chat.openai.com/share/bdcba433-a038-4d85-9119-02b17f98e2e4

# Loading in the cleaned data without one hot encoding
```{r}
path <- "/Users/justi/OneDrive/Desktop/colabo_data/data/"
dffile <- "cleaned_without_onehotEncoding_with_factor_variables.rda"
load(file = here(path, dffile))
dfr = dfr %>% dplyr::select(-c("dist_wasted_decile", "wasted_decile", "mean_wasted_dist", "o_wasted", "o_underweight", "o_stunted"))

dfr
```
## Functions for imputing missing values (and visualizing them)
```{r}
# Function to impute missing values by sampling from the empirical distribution of each column
impute_missing_values <- function(df) {
  # Apply a function across all columns using dplyr's mutate_all
  df %>% mutate_all(function(column) {
    if(any(is.na(column))) {  # Check if there are any NA values in the column
      # Non-missing values
      non_missing <- na.omit(column)
      # Sample from non-missing values to replace NA values
      # Sample size equals the number of missing values
      column[is.na(column)] <- sample(non_missing, sum(is.na(column)), replace = TRUE)
    }
    return(column)
  })
}

# Function to get indices of NAs using dplyr, only returning columns with NAs
get_na_indices_dplyr <- function(df) {
  df %>%
    summarise(across(everything(), ~ if (any(is.na(.))) list(which(is.na(.))) else NULL)) %>%
    as.list() %>%
    discard(is.null)
}
```

## Indices of the missing values for each of the variables
```{r}
dfr_naindices = dfr %>% get_na_indices_dplyr() 
dfr_naindices
```

# Names of the variables with missing values
```{r}
dfr_naindices %>% names()
```


## Imputed dfr using emperical distribution to impute missing values 
```{r}
imputed_dfr = dfr %>% impute_missing_values()

imputed_dfr
```

```{r}
imputed_dfr %>% is.na() %>% colSums() # check over the number of missing values
```

```{r}
factor_vars <- names(imputed_dfr)[sapply(imputed_dfr, is.factor)]


df_one_hot <- dummy_cols(imputed_dfr, select_columns = factor_vars, remove_first_dummy = FALSE, remove_selected_columns = TRUE)


df_one_hot
```





# Histogram distribution of the imputed missing values
```{r}
# histo_dir = "/Users/justi/OneDrive/Desktop/colabo_infant_malnutrition/missingNA Imputation with emperical distribution/"
# width = 10
# height = 10 
# 
# histogram <- vector(mode = "list")
# for(variable in dfr_naindices %>% names()){
#  
#  #Histogram on the formerly missing values
#  histogram[[variable]] = imputed_dfr[dfr_naindices[[variable]][[1]], variable] %>% 
#   dplyr::pull() %>% hist(main = paste0("Histogram of Imputed Variable (Emperical Distribution): ", variable))
#  
#  histogram[[variable]] %>% print() 
#  
#  # ggsave(paste0(variable, "_NAHistogram.pdf"), width = width,device = "pdf", height = height, 
#  #        path =histo_dir)
#  # 
#  # histogram[[variable]] %>% print()
#  # 
#  # dev.off()
#    
# }
```

# Save the new data
```{r}
path <- "/Users/justi/OneDrive/Desktop/colabo_data/data/"
# path <- "data/DHS-2019-21/"
dffile <- "imputed_data_with_onehotEncoding.rda"
save(dfr, file = here(path, dffile))
```

