---
title: "3.5-validation_NA_imputation"
author: "Justin Guerra"
date: "2023-09-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
library(Hmisc)
library(rms)
library(glmnet)
library(dplyr)
library(imputeTS)
library(mice)
library(ROCit)
library(pROC)
```

```{r message=FALSE, cache=F}
source('./mdl-evaluation.R')
```

```{r}
#path <- "/Users/justi/OneDrive/Desktop/colabo_data/data/"
path <- "data/DHS-2019-21/"
dffile <- "recoded.rda"
load(file = here(path, dffile))
```

```{r}
model_vars <- c("maternal_height_4feet8inches_to_less_5feetinches",
                "maternal_height_less_4feet8inches",
                "maternal_edu_no",
                "maternal_edu_1_7",
                "maternal_edu_greater_7_10",
                "sex_male",
                "pre_birth_interval_less_than_equal_to_24_months",
                "birth_weight_less_than_1800_g",
                "birth_weight_1800_g_2500_g",
                "num_siblings_two_or_more",
                "low_caste",
                "toliet_access_no",
                "house_partially_finished_no",
                "separate_kitchen_no",
                "cooking_fuel_solid",
                "use_soap",
                "Northeast_focus",
                "Other_Focus",
                "mean_district_CIAF_40_49.9",
                "mean_district_CIAF_50_59.9",
                "mean_district_CIAF_60_69.9",
                "mean_district_CIAF_70_79.9",
                "mean_district_CIAF_80_89.9",
                "ciaf")

model_coeffs <- c(intercept = -1.62,  
                  maternal_height_4feet8inches_to_less_5feetinches = 0.34, 
                  maternal_height_less_4feet8inches = 0.79,
                  maternal_edu_no = 0.45,
                  maternal_edu_1_7 = 0.30,
                  maternal_edu_greater_7_10 = 0.17,
                  sex_male = 0.10,
                  pre_birth_interval_less_than_equal_to_24_months = 0.23,
                  birth_weight_less_than_1800_g = 0.88,
                  birth_weight_1800_g_2500_g = 0.46,
                  num_siblings_two_or_more = 0.07,
                  low_caste = 0.14,
                  toliet_access_no = 0.18,
                  house_partially_finished_no = 0.12,
                  separate_kitchen_no = 0.07,
                  cooking_fuel_solid = 0.07,
                  use_soap = 0.07,
                  Northeast_focus = -0.16,
                  Other_Focus = -0.23,
                  mean_district_CIAF_40_49.9 = 0.29,
                  mean_district_CIAF_50_59.9 = 0.60,
                  mean_district_CIAF_60_69.9 = 0.87,
                  mean_district_CIAF_70_79.9 = 1.11,
                  mean_district_CIAF_80_89.9 = 1.64)

df_model <- df[, model_vars] 

```

```{r}
df_model %>% is.na() %>% colSums()
```



```{r}
df_modelFactor = df_model %>% mutate_if(is.integer, as.factor) 
df_imp <- mice(df_modelFactor,
     m = 3,
     maxit = 3, method = c("logreg", "logreg", "","", "","","logreg","logreg", "logreg","logreg", "logreg", "logreg", "","logreg", "logreg","","","","", "","","","","logreg"))

```
```{r}
df_modelImpNumeric <- complete(df_imp,3) %>% 
  mutate_if(is.factor, as.character) %>% 
  mutate_if(is.character, as.integer)

df_modelImpNumeric
```



```{r}
# Function to calculate the predicted the log odds (linear term of the model)
calc_log_odds <- function(coefficients, data) {
  # Extract the intercept from the coefficients
  intercept <- coefficients[1]
  
  # Extract the predictor variables from the coefficients
  predictors <- coefficients[-1]
  
  # Calculate the linear predictor using the coefficients and predictor values
  linear_predictor <- intercept + rowSums(predictors * data)
  
  return(linear_predictor)
}

# Function to calculate the predicted probabilities given the log odds
calc_pred_probs <- function(log_odds) {
  # Apply the logistic link function to get the predicted probabilities
  probabilities <- 1 / (1 + exp(-log_odds))
  return(probabilities)
}
```


```{r}
data0 <- df_modelImpNumeric
pred0 <- calc_log_odds(model_coeffs, data0)
prob0 <- calc_pred_probs(pred0)
```



```{r}
mdl_folderImp = "/Users/justi/OneDrive/Desktop/colabo_infant_malnutrition/mdl_validationImputation/"
dir.create(mdl_folderImp)


# Generate the data frame with the data needed for the calibration and ROC plots
plot_dataImp <- data.frame(out = data0$ciaf, logodds = pred0, prob = prob0)

cal_plot(base_model,plot_dataImp, "prob", model_label = '', dir = mdl_folderImp, fn = "cal_plotImputed.pdf")
cal_c0 <- cal_coeff(plot_dataImp, "prob", mdl_folderImp, "cal_plot_coefficientsImputed.txt")
print(cal_c0)

roc_plot(data0$ciaf, prob0, dir = mdl_folderImp, fn = "roc_plotImputed.pdf")
```

```{r}
conf_matrix(plot_dataImp$out, plot_dataImp$prob, 0.5, mdl_folderImp, "conf_matrixImp.txt")
```

