---
title: "Data imputation"
author: "Justin Guerra, Arnav Gupta, Andres Colubri"
output: html_document
date: "2024-03-06"
---

```{r setup, include=FALSE}
library(mice)
library(missForest)
library(missMDA)
library(here) 
```

https://chat.openai.com/share/bdcba433-a038-4d85-9119-02b17f98e2e4

```{r}
path <- "data/DHS-2019-21/"
dffile <- "cleaned.rda"
load(file = here(path, dffile))
dfc
```

```{r}
na_count <- sum(is.na(dfc))
na_count
```

```{r}
method <- c()
for (col_name in names(dfc)) {
  column <- dfc[[col_name]]
  
  is_binary <- all((column %in% c(0, 1)) | is.na(column))
  
  if (is_binary) {
    method <- c(method, "logreg")
  } else {
    method <- c(method, "norm")
  }
}

method
```

```{r}
set.seed(123)  # Setting a seed for reproducibility
n <- nrow(dfc)
indices <- sample(rep(1:10, length.out = n))
indices
```

```{r}
# Splitting the dataframe into a list of 10 dataframes
subsamples <- lapply(1:10, function(i) dfc[indices == i, ])
```


```{r}
df1 <- as.data.frame(subsamples[1])
dim(df1)
```

```{r}
dfimp_mice1 <- mice(df1, m = 3, maxit = 3, method=method)
```

```{r}
com <- complete(dfimp_mice1, 1)
com
```

```{r}
na_count <- sum(is.na(com))
na_count
```

```{r}
dfimp_for1 <- missForest(df1)
```



```{r}
# Estimate the number of dimensions
ncp <- estim_ncpPCA(df1, method = "EM")
print(ncp$ncp)
```

```{r}
# https://rdrr.io/cran/missMDA/man/imputeFAMD.html

result <- imputeMCA(df1, ncp = ncp$ncp)
```


```{r}
# The imputed data
imputed_data <- result$completeObs
```





```{r}

#for (i in var_1_0s %>% names()) {

  #c("logreg", "logreg", "","", "","","logreg","logreg", "logreg","logreg", "logreg", "logreg", "","logreg", "logreg","","","","", "","","","","logreg"))
  
  
  
  
 # ifelse(test = var_1_0s[[i]] %in% c(0,1) ,TRUE, FALSE) %>% print()


#}
```
